user nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log debug;
pid        /var/run/nginx.pid;

events {
	worker_connections  1024;
}

http {
	include       /etc/nginx/mime.types;
	default_type  application/octet-stream;

	log_format main '$remote_addr - $remote_user [$time_local] "$request" '
							'$status $body_bytes_sent "$scheme://$host" "$http_referer" '
							'"$http_user_agent" "$http_x_forwarded_for"';

	access_log  /var/log/nginx/access.log  main;
	error_log  /var/log/nginx/error.log debug;

	sendfile        on;
	#tcp_nopush     on;
	client_max_body_size 128M; # 原始值为15M，我们解除此限制

	# This directive appeared in version 1.25.1. @see {https://nginx.org/en/docs/http/ngx_http_v2_module.html#http2}
	# http2 on; # enable http2. 默认为off
	# http2 off;

	# nginx提供的优化示例. @see {https://nginx.org/en/docs/http/configuring_https_servers.html}
	# SSL操作会消耗额外的CPU资源。在多处理器系统上，应该运行多个工作进程，数量不少于可用的CPU核心数。最消耗CPU资源的操作是SSL握手。
	# 有两种方法可以减少每个客户端的这些操作次数：第一种是通过启用保持活动连接，在一个连接上发送多个请求；第二种是重用SSL会话参数，以避免并行和后续连接的SSL握手。
	# 会话存储在由ssl_session_cache指令配置的SSL会话缓存中，该缓存在工作进程之间共享。缓存的大小为1兆字节，大约包含4000个会话。
	# 默认的缓存超时时间为5分钟，可以通过使用ssl_session_timeout指令来增加。以下是针对具有10兆字节共享会话缓存的多核系统进行优化的示例配置
	ssl_session_cache shared:SSL:10m;
	ssl_session_timeout 10m;

	# Nginx 的默认 keepalive_timeout 值通常为 75s
	# keepalive_timeout <timeout> <header_timeout>;
	# 如果只指定一个参数，Nginx 会将其作为 timeout 何 header_timeout；如果指定两个参数，第一个是超时时间，第二个是 header_timeout
	# timeout: 服务器在保持活动连接期间等待客户端发送新请求的时间。如果在此时间内客户端未发送新的请求，服务器将关闭连接
	# header_timeout: 服务器在保持活动连接期间等待客户端发送完整请求头的最大时间。如果客户端在此时间内未完成请求头的发送，服务器将关闭连接
	keepalive_timeout  75; # 单位默认为 s，也可以指定单位，如 60000ms

	# 对于 websockets 的数据压缩，这是端到端的，nginx 仅在初始协商（upgrade）阶段起作用，而我们在 proxy.conf 中的配置是充分的
	# 开启 gzip. 这里是全局设置，适用于所有 location. 对于静态资源，则需要定义
	# @see https://chatgpt.com/share/6757f368-bbc8-800f-91b7-b437b62f00d4
	gzip_static on; # 对于本地文件，会优先查找并使用 <file>.gz 文件，避免动态压缩；对于 REST API，则会跳过。因此可以作为全局配置项
	gzip_vary on; # 添加 Vary: Accept-Encoding	
	gzip on; # 关闭为 off
	# 设置压缩级别，范围1-9，数值越大压缩比越高，但会耗费更多CPU时间
	gzip_comp_level 5;
	# 指定需要压缩的 MIME 类型. 这里仅为示例，可根据实际情况进行增减
	# rss+xml 用于表示 RSS（Really Simple Syndication） 格式的内容。这是一种用于发布经常更新的信息（如博客、新闻等）的标准格式，允许用户和应用程序订阅和获取最新内容
	gzip_types 
		text/css text/javascript text/xml text/plain
		application/javascript application/json application/xml application/rss+xml;
	# 对响应体大小进行最小值限制，当数据小于此值时不启用压缩（可选）
	gzip_min_length 1024;
	# 告知代理和浏览器请求不会因 gzip 压缩而出错
	gzip_proxied any;
	# 用于控制在特定条件下是否禁用 gzip 压缩的指令
	gzip_disable "msie6"; # 对于某些老式的浏览器，如 IE6，匹配 UA 的对应 string 后禁用 gzip
	# 更多优化（可选）
  # gzip_buffers 16 8k;
  # gzip_http_version 1.0;

	include /etc/nginx/conf.d/*.conf;
}
