/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatInput: typeof import('./src/components/ChatInput.vue')['default']
    ChatMsgItem: typeof import('./src/components/ChatMsgItem.vue')['default']
    DesktopSidebar: typeof import('./src/components/DesktopSidebar.vue')['default']
    MainList: typeof import('./src/components/MainList.vue')['default']
    MarkdownBody: typeof import('./src/components/MarkdownBody.vue')['default']
    MobileBottomTabs: typeof import('./src/components/MobileBottomTabs.vue')['default']
    MobilePageHeader: typeof import('./src/components/MobilePageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TouchSpeakOverlay: typeof import('./src/components/TouchSpeakOverlay.vue')['default']
    UAccordion: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_35a038c29b65ffae1286c8f9dd628a52/node_modules/@nuxt/ui/dist/runtime/components/Accordion.vue')['default']
    UApp: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_35a038c29b65ffae1286c8f9dd628a52/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_35a038c29b65ffae1286c8f9dd628a52/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_35a038c29b65ffae1286c8f9dd628a52/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_35a038c29b65ffae1286c8f9dd628a52/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UCheckbox: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_35a038c29b65ffae1286c8f9dd628a52/node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UContainer: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_35a038c29b65ffae1286c8f9dd628a52/node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
    UFormField: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_35a038c29b65ffae1286c8f9dd628a52/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_35a038c29b65ffae1286c8f9dd628a52/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_35a038c29b65ffae1286c8f9dd628a52/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_35a038c29b65ffae1286c8f9dd628a52/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UPopover: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_35a038c29b65ffae1286c8f9dd628a52/node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
    USelect: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_35a038c29b65ffae1286c8f9dd628a52/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    UserInfoRows: typeof import('./src/components/user/UserInfoRows.vue')['default']
    UserProfileDialog: typeof import('./src/components/user/UserProfileDialog.vue')['default']
    UserProfilePanel: typeof import('./src/components/user/UserProfilePanel.vue')['default']
    UserSettingsDialog: typeof import('./src/components/user/UserSettingsDialog.vue')['default']
    UserSettingsPanel: typeof import('./src/components/user/UserSettingsPanel.vue')['default']
    UTabs: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_35a038c29b65ffae1286c8f9dd628a52/node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    UTextarea: typeof import('./../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_35a038c29b65ffae1286c8f9dd628a52/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
  }
}
